### ISSUE TITLE
Virus Total malware detection 

### ISSUE THREAD

**Issue by Alexprox7** [trondr/DriverTool#67]
Hi I scanned the file on virustotal and told me there's a trojan https://www.virustotal.com/gui/file/bd4680b0dcf2137d79576cc65504ea494ba9866f797295b3c8875b563912657c/summary

**Comment by decimaldreamer** [comment]
MaxSecure based on India, nobody uses this trash AV. So, file is false positive.

**Comment by trondr** [comment]
Yes this is a false positive.
